sonar.projectKey=FabrizioPerezPeralta_AnzenCore
sonar.organization=fabrizioperezperalta
sonar.projectName=AnzenCore
sonar.sources=.
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**, **/.venv/**, **/assets/**, tests/**, Docs/**, media/**, htmlcov/**, infra/**, src/**, agent/**, mobile/**