sonar.projectKey=anzencore
sonar.projectName=AnzenCore
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.buildozer/**,assets/**,src/**
sonar.coverage.exclusions=tests/**,mobile/**,src/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
